let C,U,V; const $=id=>document.getElementById(id);
async function init(){try{C=await fetch('/api/config').then(r=>r.json());U=C.user;if(U){$('login').hidden=true;$('shop').hidden=false;render();orders()}else $('login').innerHTML='<h3>Compra en Ventas Yupi Dilan</h3><p>Inicia sesión con Google para guardar y consultar tus pedidos.</p><a class="btn primary" href="/auth/google">Continuar con Google →</a>'}catch(e){$('login').innerHTML='<h3>La tienda está en modo mantenimiento</h3><p>Estamos terminando la conexión del sistema de recargas.</p>'}}
function render(){const packs=C.products.slice(0,4),ids=C.products.slice(4,10),booyah=C.products.slice(10);const card=p=>`<article class="product"><small>💎 FREE FIRE</small><h3>${p[1]}</h3><div class="price">$${p[2]} <small>MXN</small></div><button onclick="buy('${p[0]}')">Comprar ahora</button></article>`;$('products').innerHTML=`<div class="catalog-title"><h3>🔥 Paquetes de diamantes</h3></div><div class="grid">${packs.map(card).join('')}</div><div class="catalog-title"><h3>💎 Diamantes x ID</h3></div><div class="grid">${ids.map(card).join('')}</div><div class="catalog-title"><h3>🎟️ Pase Booyah</h3></div><div class="grid">${booyah.map(card).join('')}</div>`}
async function check(){const id=$('pid').value.trim();$('who').textContent='Comprobando ID...';try{const r=await fetch('/api/validate-id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:id})}),d=await r.json();if(!r.ok||!d.valid){V=null;$('who').textContent='❌ '+(d.error||'ID no encontrado');return}V={id,name:d.player_name};$('who').textContent='✓ Jugador: '+V.name}catch{$('who').textContent='❌ No se pudo comprobar el ID'}}
function buy(k){if(!V)return alert('Primero verifica tu ID de Free Fire.');const p=C.products.find(x=>x[0]===k);$('pk').value=k;$('pay').innerHTML=`<div class="pay"><b>Total: $${p[2]} MXN</b><br><br>🏦 ${C.payment.bank||'Datos de transferencia'}<br>👤 ${C.payment.holder||''}<br>💳 ${C.payment.card||''}<br>📝 Concepto: ${C.payment.concept||''}<br><br>🎮 ${V.name} · ID ${V.id}</div>`;$('modal').classList.add('show')}
function closeM(){$('modal').classList.remove('show')}
$('form').onsubmit=async e=>{e.preventDefault();const f=new FormData();f.append('productKey',$('pk').value);f.append('playerId',V.id);f.append('playerName',V.name);f.append('receipt',$('file').files[0]);const r=await fetch('/api/orders',{method:'POST',body:f}),d=await r.json();if(!r.ok)return alert(d.error||'No se pudo crear el pedido');closeM();$('file').value='';alert('Pedido '+d.orderId+' creado. Esperando confirmación del Admin.');orders()}
async function orders(){const r=await fetch('/api/orders');if(!r.ok)return;const d=await r.json();$('orders').innerHTML=d.length?d.map(o=>`<div class="order-row"><b>${o.public_id}</b> · ${o.product} · $${o.price} MXN<br>🎮 ${o.player_name} · ID ${o.player_id}<br><span class="status">${o.status}</span></div>`).join(''):'Aún no tienes pedidos.'}
function adm(){const c=prompt('Código de Administración');if(!c)return;fetch('/auth/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:c})}).then(r=>r.ok?location.href='/admin.html':alert('Código incorrecto'))}
init();
